name: xmlc
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip=24.2

  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - torchvision=0.15.2
  - torchtext=0.15.2
  - torchdata=0.6.1

  - blas=1.0=mkl
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - intel-openmp=2023.1.0

  - numpy=1.23.5
  - scipy=1.10.1
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - tqdm=4.65.0
  - pyyaml=6.0.1

  - sentencepiece=0.1.99
  - nltk=3.9.1
  - gensim=4.3.3

  - cython=3.0.11
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - logzero=1.7.0
